config/routes.rb
Mother::Application.routes.draw do
  

  resources :children

  resources :mother1s

  resources :bouquets
 get "/cost", to: "bouquets#cost"
 

   root :to => 'welcome#index'

end

app/models/bouquet.rb
class Bouquet < ActiveRecord::Base
  attr_accessible :name, :number_of_flowers, :price
  validates :price, :numericality => true, :on => :update
  validates :number_of_flowers, :numericality => true, :on => :update
  end

app/models/child.rb
class Child < ActiveRecord::Base
  attr_accessible :age, :name, :mother1_id
  belongs_to :mother1
end

app/models/mother1.rb
class Mother1 < ActiveRecord::Base
  attr_accessible :age, :name, :surname, :job, :children_id
 	has_many :children, :dependent => :destroy
 	validates :age, { numericality: { greater_than: 10 } }
 	validates :age, :numericality => true, :on => :update
end

app/models/one.rb
class One < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bouquets_controller.rb
class BouquetsController < ApplicationController
def index
    @Bouquets = Bouquet.all
p " "
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @Bouquets }
    end

end

def show 
  
  p  @Bouquets = Bouquet.find(params[:id])
      @money = (@Bouquets.number_of_flowers * @Bouquets.price)
        respond_to do |format|
      format.html 
      format.json { render json: @Bouquets }
    end
  end

  
  def new
  
  p @Bouquets = Bouquet.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @Bouquets }
    end
  end


  def edit
    @Bouquets = Bouquet.find(params[:id])
  end

 

  def create
    @Bouquets = Bouquet.new(params[:bouquet])
 
    respond_to do |format|
      if @Bouquets.save
        format.html { redirect_to @Bouquets, notice: 'Bouquet was successfully created.' }
        format.json { render json: @Bouquets, status: :created, location: @Bouquets }
      else
        format.html { render action: "new" }
        format.json { render json: @Bouquets.errors, status: :unprocessable_entity }
      end
    end
  end


  

def update
    @Bouquets = Bouquet.find(params[:id])

    respond_to do |format|
      if @Bouquets.update_attributes(params[:Bouquet])
        format.html { redirect_to @Bouquets, notice: 'Bouquet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @Bouquets.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @Bouquets = Bouquet.find(params[:id])
    @Bouquets.destroy

    respond_to do |format|
      format.html { redirect_to bouquets_url }
      format.json { head :no_content }
    end
  end

  def cost
   @Bouquets  = Bouquet.find(params[:id])
    @money = (@Bouquets.number_of_flowers * @Bouquets.price)
end

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def index
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end
  def show
    @child = Child.find(params[:id])
    @mother1_id = params[:mother1_id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/new
  # GET /children/new.json
  def new
    @child = Child.new
    @mother1_id = params[:mother1_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(params[:child])
    @mother1_id = params[:mother1_id]

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render json: @child, status: :created, location: @child }
      else
        format.html { render action: "new" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.json
  

def update
    @child = Child.find(params[:id])

    respond_to do |format|
      if @child.update_attributes(:name => params[:child][:name], :age => params[:child][:age])
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/mother1s_controller.rb
class Mother1sController < ApplicationController
  # GET /mother1s
  # GET /mother1s.json
  def index
    @mother1s = Mother1.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mother1s }
    end
  end

  # GET /mother1s/1
  # GET /mother1s/1.json
  def show
    @mother1 = Mother1.find(params[:id])
    @children = Child.where(:mother1_id => params[:id])

    #@children_id = params[:children_id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mother1 }
    end
  end

  # GET /mother1s/new
  # GET /mother1s/new.json
  def new
    @mother1 = Mother1.new

    #@children_id = params[:children_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mother1 }
    end
  end

  # GET /mother1s/1/edit
  def edit
    @mother1 = Mother1.find(params[:id])
  end

  # POST /mother1s
  # POST /mother1s.json
  def create
    @mother1 = Mother1.new(params[:mother1])

    #@children_id = params[:children_id]

    respond_to do |format|
      if @mother1.save
        format.html { redirect_to @mother1, notice: 'Mother was successfully created.' }
        format.json { render json: @mother1, status: :created, location: @mother1 }
      else
        format.html { render action: "new" }
        format.json { render json: @mother1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mother1s/1
  # PUT /mother1s/1.json
  def update
    @mother1 = Mother1.find(params[:id])

    respond_to do |format|
      if @mother1.update_attributes(params[:mother1])
        format.html { redirect_to @mother1, notice: 'Mother was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mother1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mother1s/1
  # DELETE /mother1s/1.json
  def destroy
    @mother1 = Mother1.find(params[:id])
    @mother1.destroy

    respond_to do |format|
      format.html { redirect_to mother1s_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouquet_helper.rb
module BouquetHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/mother1s_helper.rb
module Mother1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bouquets/_cost_result.html.erb
<h1><%=@money%></h1>

app/views/bouquets/_form.html.erb
<%= form_for(@Bouquets) do |f| %>
  <% if @Bouquets.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@Bouquets.errors.count, "error") %> prohibited this bouquet from being saved:</h2>

      <ul>
      <% @Bouquets.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<table class="table">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :number_of_flowers %><br />
    <%= f.text_field :number_of_flowers %>
  </div>
      
      <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
     

  <div class="actions">
    <%= f.submit %>
  </div>
  </table>
<% end %>

app/views/bouquets/cost.js.erb
alert("<%= @money%>")

app/views/bouquets/edit.html.erb
<h1>Editing bouquet</h1>

<%= render 'form' %>

<%= link_to 'Back', bouquets_path, :class=>"btn btn-danger" %>

app/views/bouquets/index.html.erb
<h1>Bouquets</h1>

<table class="table table-bordered">

<tr>
    <th>Name of the flower</th>
    <th>Number of the flowers</th>
    <th>price</th>
</tr>
  

  <% @Bouquets.each do |bouquet| %>
  
  <tr id="<%=bouquet.id %>"</tr>
    <td><%= bouquet.name %></td>
    <td><%= bouquet.number_of_flowers %></td>
    <td><%= bouquet.price %></td>
    <td><i><%= link_to 'Show', bouquet %></i></td>
    <td><i><%= link_to 'Edit', edit_bouquet_path(bouquet)%></i></td>
    <td><i><%= link_to 'Destroy', bouquet, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"text-error"%></i></td>
    <td><i><span class="costAction">The price of the bouquet</span></i></td>
      </tr>
<% end %>
</table>
<br />
<%= link_to 'New bouquet', new_bouquet_path,  :class=>"btn btn-danger" %>

app/views/bouquets/new.html.erb
<h1>New bouquet</h1>

<%= render 'form' %>

<%= link_to 'Back', bouquets_path, :class => "btn btn-danger"%>

app/views/bouquets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @Bouquets.name %>
</p>


<p>
  <b>Number of flowers:</b>
  <%= @Bouquets.number_of_flowers %>
</p>

<p>
  <b>Price:</b>
  <%= @Bouquets.price %>
</p>

<p>
<b>Price for bouquet</b>
<%= @money %>
</p>

<input id="myElement" type="button" oncklick="make_calc();" value="Review Bouquet" class="btn btn-danger"/>
	<script>
		$("#myElement").on("click", function(){
			if ((<%= @money %>)>=100) {
				alert('Nice bouquet!');
			}
			else {
				alert('Bad bouquet!');
			}
		});
	</script>

<%= link_to 'Back',bouquets_path, :class=>"btn btn-danger"%>

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="center">
   </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
      
      <%= f.hidden_field(:mother1_id, :value => @mother1_id) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child,  :class=>"btn btn-danger" %> |
<%= link_to 'Back', children_path,  :class=>"btn btn-danger" %>

app/views/children/index.html.erb
<h1>Сhildren</h1>

<table class="table table-bordered">
 
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @children.each do |child| %>
  <tr>
    <td><%= child.name %></td>
    <td><%= child.age %></td>
    <td><i><%= link_to 'Show', child, :class=>"text-success" %></i></td>
    <td><i><%= link_to 'Edit', edit_child_path(child) %></i></td>
    <td><i><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"text-error" %></i></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Child', new_child_path,  :class=>"btn btn-danger"%>
<%= link_to 'Mothers ', mother1s_path,  :class=>"btn btn-danger"%>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path,  :class=>"btn btn-danger" %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @child.name %>
</p>


<p>
  <b>Age:</b>
  <%= @child.age %>
</p>

<p>
  <b>Name of mother:</b>
  <%= @child.mother1.name %>
</p>

<%= link_to 'Edit', edit_child_path(@child),  :class=>"btn btn-danger"%>
<%= link_to 'Back', children_path,  :class=>"btn btn-danger"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mother" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner" >
        <div class="container">
          <a class="btn btn-navbar" >
            <div id="ibm-masthead"> 
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Mother</a>
          <div class="container nav-collapse">
            <ul class="nav">         
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>       
                         
            
          
          </div><!--/span-->
        </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/mother1s/_form.html.erb
<%= form_for(@mother1) do |f| %>
  <% if @mother1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mother1.errors.count, "error") %> prohibited this mother1 from being saved:</h2>

      <ul>
      <% @mother1.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <table class="table">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </div>
  
   <%= f.hidden_field(:children_id, :value => @child_name) %>

  <div class="actions">
    <%= f.submit %>
  </div>
  </table>
 <% end %>

app/views/mother1s/edit.html.erb
<h1>Editing mother</h1>

<%= render 'form' %>

<%= link_to 'Show', @mother1,  :class=>"btn btn-danger" %> |
<%= link_to 'Back', mother1s_path,  :class=>"btn btn-danger" %>

app/views/mother1s/index.html.erb
<h1>Mothers</h1>

<table class="table table-bordered">
 
  <tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Age</th>
    <th>Job</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<% @mother1s.each do |mother1| %>
  <tr>
    <td><%= mother1.name %></td>
    <td><%= mother1.surname %></td>
    <td><%= mother1.age %></td>
    <td><%= mother1.job %></td>
    <td><i><%= link_to 'Show', mother1 %></i></td>
    <td><i><%= link_to 'Edit', edit_mother1_path(mother1) %></i></td>
    <td><i><%= link_to 'Destroy', mother1, method: :delete, data: { confirm: 'Are you sure?' } %></i></td>
    <td><i><%= link_to 'Add child', {:controller => :children, :action => :new, :mother1_id => mother1.id} %></i></td>
     </tr>
<% end %>
</table>

<br />


<%= link_to 'New Mother', new_mother1_path, :class=>"btn btn-danger"%>
<%= link_to 'Children', children_path, :class=>"btn btn-danger" %>

app/views/mother1s/new.html.erb
<h1>New mother</h1>

<%= render 'form' %>

<%= link_to 'Back', mother1s_path,  :class=>"btn btn-danger" %>

app/views/mother1s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mother1.name %>
</p>
<%link_to 'Add', children_path %>
<p>
  <b>Surname:</b>
  <%= @mother1.surname %>
</p>

<p>
  <b>Age:</b>
  <%= @mother1.age %>
</p>

<p>
  <b>Job:</b>
  <%= @mother1.job %>
</p>

<p>
  <b>Names of children:</b>
  <table>
  <tr>
    <th>Name</th>
    <th>Age</th>
  </tr>

<% @children.each do |child| %>
  <table>
  <tr>
    <td><%= child.name %></td>
    <td><%= child.age %></td>
  </tr>
  <% end %>
</table>
</table>
</p>
<%= link_to 'Edit', edit_mother1_path(@mother1),  :class=>"btn btn-danger" %> |
<%= link_to 'Back', mother1s_path, :class=>"btn btn-danger" %>

app/views/welcome/index.html.erb
<h1>Mothers and children</h1>
<%= link_to 'Mothers', mother1s_path, :class=>"btn btn-danger"%>
<%= link_to 'Children', children_path, :class=>"btn btn-danger"%>
<h2>Bouquet</h2>
<%= link_to 'Bouquets', bouquets_path, :class=>"btn btn-danger" %>